import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#081120',
  },
  content: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  card: {
    width: '100%',
    maxWidth: 760,
    backgroundColor: '#0f172a',
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  kicker: {
    color: '#38bdf8',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 8,
  },
  title: {
    color: '#f8fafc',
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'center',
  },
  subtitle: {
    color: '#cbd5e1',
    fontSize: 16,
    lineHeight: 23,
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 18,
  },
  section: {
    marginTop: 16,
  },
  sectionTitle: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  input: {
    backgroundColor: '#111c33',
    borderWidth: 1,
    borderColor: '#24324d',
    borderRadius: 16,
    color: '#f8fafc',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  roundsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  roundButton: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#1d4ed8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  roundButtonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  roundButtonText: {
    color: '#eff6ff',
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 30,
  },
  roundsInput: {
    flex: 1,
    minWidth: 90,
    maxWidth: 160,
    backgroundColor: '#111c33',
    borderWidth: 1,
    borderColor: '#24324d',
    borderRadius: 16,
    color: '#f8fafc',
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 18,
    fontWeight: '700',
  },
  helperText: {
    color: '#94a3b8',
    fontSize: 13,
    marginTop: 8,
  },
  difficultyRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  flexItem: {
    flexGrow: 0,
    flexBasis: '30%',
    minWidth: 110,
    maxWidth: 180,
  },
  modeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  option: {
    flexGrow: 1,
    flexBasis: '48%',
    minWidth: 220,
    backgroundColor: '#111c33',
    borderWidth: 1,
    borderColor: '#24324d',
    borderRadius: 18,
    padding: 16,
  },
  optionCompact: {
    flexGrow: 0,
    flexBasis: 'auto',
    minWidth: 0,
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  optionSelected: {
    backgroundColor: '#1e3a8a',
    borderColor: '#60a5fa',
  },
  optionPressed: {
    opacity: 0.9,
  },
  optionLabel: {
    color: '#e2e8f0',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
    textAlign: 'center',
  },
  optionLabelSelected: {
    color: '#eff6ff',
  },
  optionDescription: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  summaryCard: {
    marginTop: 20,
    padding: 16,
    borderRadius: 18,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#24324d',
  },
  summaryTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
  },
  summaryText: {
    color: '#cbd5e1',
    fontSize: 14,
    marginBottom: 4,
  },
  historyTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  historyTab: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#24324d',
    backgroundColor: '#111c33',
  },
  historyTabPressed: {
    opacity: 0.9,
  },
  historyTabSelected: {
    backgroundColor: '#1e3a8a',
    borderColor: '#60a5fa',
  },
  historyTabLabel: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '700',
  },
  historyTabLabelSelected: {
    color: '#eff6ff',
  },
  historyList: {
    marginTop: 12,
    gap: 10,
  },
  historyItem: {
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#24324d',
    borderRadius: 18,
    padding: 14,
    gap: 8,
  },
  historyItemTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  historyPlayer: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
    flexShrink: 1,
  },
  historyScoreBadge: {
    backgroundColor: '#1d4ed8',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  historyScoreText: {
    color: '#eff6ff',
    fontSize: 14,
    fontWeight: '800',
  },
  historyMeta: {
    color: '#94a3b8',
    fontSize: 13,
  },
  historyEmptyState: {
    borderWidth: 1,
    borderColor: '#24324d',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#111827',
    alignItems: 'center',
  },
  historyEmptyText: {
    color: '#94a3b8',
    fontSize: 13,
    textAlign: 'center',
  },
  primaryButton: {
    marginTop: 18,
    backgroundColor: '#22c55e',
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#052e16',
    fontSize: 18,
    fontWeight: '800',
  },
  footerNote: {
    color: '#64748b',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 12,
  },
  gameScreenContainer: {
    flex: 1,
    backgroundColor: '#081120',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  gameCard: {
    width: '100%',
    maxWidth: 760,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
  },
  gameCenteredBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  gameQuestionText: {
    color: '#e2e8f0',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
  },
  gameQuestionSubtext: {
    color: '#94a3b8',
    fontSize: 14,
    marginTop: 6,
    textAlign: 'center',
  },
  gameInputBlock: {
    marginTop: 16,
    width: '100%',
    maxWidth: 360,
  },
  keypadContainer: {
    width: '100%',
    gap: 12,
  },
  keypadDisplayRow: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#24324d',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 6,
  },
  keypadLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  keypadValue: {
    color: '#f8fafc',
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
  },
  keypadGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
  },
  keypadButton: {
    flexBasis: '30%',
    minWidth: 86,
    minHeight: 58,
    borderRadius: 16,
    backgroundColor: '#111c33',
    borderWidth: 1,
    borderColor: '#24324d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  keypadButtonSpecial: {
    backgroundColor: '#182744',
  },
  keypadButtonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  keypadButtonText: {
    color: '#eff6ff',
    fontSize: 22,
    fontWeight: '800',
  },
  keypadActionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  keypadActionButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: '#111c33',
    borderWidth: 1,
    borderColor: '#24324d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  keypadActionButtonPrimary: {
    backgroundColor: '#22c55e',
    borderColor: '#22c55e',
  },
  keypadActionText: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '700',
  },
  keypadActionTextPrimary: {
    color: '#052e16',
    fontSize: 15,
    fontWeight: '800',
  },
  gameCenteredActions: {
    marginTop: 16,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  vfActionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    flexWrap: 'wrap',
  },
  multipleGrid: {
    marginTop: 18,
    width: '100%',
    maxWidth: 520,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
  },
  multipleOption: {
    flexGrow: 0,
    flexBasis: '48%',
    minWidth: 180,
    maxWidth: 240,
    marginBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 72,
  },
  multipleOptionLabel: {
    color: '#e2e8f0',
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
});

export default styles;
